
---
mail:
    gmail:
        email: bronsmailsupreme@gmail.com
        password: bruhMoment
    postmark:
        api:
            token: postmark_token
    sender:
        email: bronsmailsupreme@gmail.com

---
status:
    INVALID_TOKEN: 400
    INVALID_ACTION: 402
    OK: 200


---
grails:
    profile: web
    codegen:
        defaultPackage: ttreport
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    cors:
        enabled: true
        allowedOrigins:
            -http://localhost:8080
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
                - text/html
                - application/xhtml+xml
            js: text/javascript
            json:
                - application/json
                - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
                - application/hal+json
                - application/hal+xml
            xml:
                - text/xml
                - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    username: tomcat
    password: 't4mc0t_P0ssw4rd'

environments:
    development:
        dataSource:
            logSql: true
            dbCreate: update
            url: jdbc:mysql://localhost:3306/users
            username: tomcat
            password: 't4mc0t_P0ssw4rd'
    test:
        dataSource:
            logSql: true
            dbCreate: create-drop
            url: jdbc:mysql://localhost:3306/grails_test
            username: tomcat
            password: 't4mc0t_P0ssw4rd'
    production:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost:3306/ttreport
            pooled: true
            username: tomcat
            password: 't4mc0t_P0ssw4rd'
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED